-- CONNECT SYS/SYS AS SYSDBA
-- DROP USER c##project CASCADE;
-- CREATE USER c##project IDENTIFIED BY project
-- DEFAULT TABLESPACE USERS;
-- GRANT CONNECT,RESOURCE TO c##project;
-- GRANT All PRIVILEGES TO c##project;
-- CONNECT c##project/project




--PARTIE 1 


CREATE TABLE Role (
    Role_ID NUMBER NOT NULL,
    Name VARCHAR2(10) NOT NULL,
    Power_Type VARCHAR2(10) NOT NULL,
    Attack_Type VARCHAR2(10) NOT NULL
);
ALTER TABLE Role ADD CONSTRAINT Role_ID_PK PRIMARY KEY (Role_ID);




CREATE TABLE God (
    God_ID NUMBER NOT NULL,
    Name VARCHAR2(25) NOT NULL,
    Description VARCHAR2(75),
    Pantheon VARCHAR2(10) NOT NULL,
    Role_ID NUMBER NOT NULL
);
ALTER TABLE God ADD CONSTRAINT God_ID_PK PRIMARY KEY (God_ID);
ALTER TABLE God ADD CONSTRAINT God_Role_FK FOREIGN KEY (Role_ID) REFERENCES Role(Role_ID);





CREATE TABLE Effect (
    Effect_ID NUMBER NOT NULL,
    Name VARCHAR2(30) NOT NULL,
    Effect_Type VARCHAR2(10) NOT NULL
);
ALTER TABLE Effect ADD CONSTRAINT Effect_ID_PK PRIMARY KEY (Effect_ID);





CREATE TABLE Item (
    Item_ID NUMBER NOT NULL,
    Name VARCHAR2(50) NOT NULL,
    Price NUMBER NOT NULL
);
ALTER TABLE Item ADD CONSTRAINT Item_ID_PK PRIMARY KEY (Item_ID);





CREATE TABLE Item_Effect (
    Item_ID NUMBER NOT NULL,
    Effect_ID NUMBER NOT NULL,
    Effect_Value NUMBER NOT NULL
);
ALTER TABLE Item_Effect ADD CONSTRAINT Item_Effect_Item_ID_FK FOREIGN KEY (Item_ID) REFERENCES Item(Item_ID);
ALTER TABLE Item_Effect ADD CONSTRAINT Item_Effect_Effect_ID_FK FOREIGN KEY (Effect_ID) REFERENCES Effect(Effect_ID);
ALTER TABLE Item_Effect ADD CONSTRAINT Item_Effect_ItemEffectIDEffectValue_PK PRIMARY KEY (Item_ID, Effect_ID);





CREATE TABLE Player (
    Player_ID NUMBER NOT NULL,
    Username VARCHAR2(50) NOT NULL,
    Age NUMBER NOT NULL,
    Join_Date DATE NOT NULL
);
ALTER TABLE Player ADD CONSTRAINT Player_ID_PK PRIMARY KEY (Player_ID);





CREATE TABLE Match (
    Match_ID NUMBER NOT NULL,
    Start_Time DATE NOT NULL,
    End_Time DATE
);
ALTER TABLE Match ADD CONSTRAINT Match_ID_PK PRIMARY KEY (Match_ID);






CREATE TABLE Player_Match (
    Player_ID NUMBER NOT NULL,
    Match_ID NUMBER NOT NULL,
    God_ID NUMBER NOT NULL
);

ALTER TABLE Player_Match ADD CONSTRAINT Player_Match_Player_ID_FK FOREIGN KEY (Player_ID) REFERENCES Player(Player_ID);
ALTER TABLE Player_Match ADD CONSTRAINT Player_Match_Match_ID_FK FOREIGN KEY (Match_ID) REFERENCES Match(Match_ID);
ALTER TABLE Player_Match ADD CONSTRAINT Player_Match_God_ID_FK FOREIGN KEY (God_ID) REFERENCES God(God_ID);
ALTER TABLE Player_Match ADD CONSTRAINT Player_Match_PlayerMatchGod_ID_PK PRIMARY KEY (Player_ID, Match_ID, God_ID);







ALTER TABLE Role ADD CONSTRAINT Role_Name_CK CHECK (Name IN ('ASSASSIN', 'GUARDIAN', 'HUNTER', 'MAGE', 'WARRIOR'));
ALTER TABLE Role ADD CONSTRAINT Role_Power_Type_CK CHECK (Power_Type IN ('PHYSICAL', 'MAGICAL'));
ALTER TABLE Role ADD CONSTRAINT Role_Attack_Type_CK CHECK (Attack_Type IN ('RANGED', 'MELEE'));


ALTER TABLE God ADD CONSTRAINT God_Pantheon_CK CHECK (Pantheon IN ('ARTHURIAN', 'BABYLONIAN', 'CHINESE', 'CELTIC', 'EGYPTIAN', 'GREEK', 'GREAT OLD ONES', 'HINDU', 'JAPANESE', 'MAYA', 'NORSE', 'POLYNESIAN', 'ROMAN', 'SLAVIC', 'VOODOO', 'YORUBA'));


ALTER TABLE Effect ADD CONSTRAINT Effect_Type_CK CHECK (Effect_Type IN ('OFFENSIVE', 'DEFENSIVE', 'UTILITY'));


ALTER TABLE Item ADD CONSTRAINT Item_Price_CK CHECK (Price > 0);



ALTER TABLE Item_Effect ADD CONSTRAINT Item_Effect_Value_CK CHECK (Effect_Value > 0);




ALTER TABLE Player ADD CONSTRAINT Player_Username_UK UNIQUE (Username);
ALTER TABLE Player ADD CONSTRAINT Player_Age_CK CHECK (Age > 13);






--PARTIE 2 

CREATE SEQUENCE SEQ_Role_ID START WITH 10 INCREMENT BY 10 MAXVALUE 1000 NOCYCLE;
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'ASSASSIN', 'PHYSICAL', 'MELEE');
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'GUARDIAN', 'MAGICAL', 'MELEE');
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'GUARDIAN', 'MAGICAL', 'RANGED');
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'HUNTER', 'PHYSICAL', 'RANGED');
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'MAGE', 'MAGICAL', 'MELEE');
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'MAGE', 'MAGICAL', 'RANGED');
INSERT INTO Role(Role_ID, Name, Power_Type, Attack_Type) VALUES (SEQ_Role_ID.NEXTVAL, 'WARRIOR', 'PHYSICAL', 'MELEE');

CREATE SEQUENCE SEQ_Match_ID START WITH 10000 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE;
INSERT INTO Match(Match_ID, Start_Time, End_Time) VALUES (SEQ_Match_ID.NEXTVAL, TO_DATE('2023-10-20 14:30', 'YYYY-MM-DD HH24:MI'), TO_DATE('2023-10-20 15:15', 'YYYY-MM-DD HH24:MI'));
INSERT INTO Match(Match_ID, Start_Time, End_Time) VALUES (SEQ_Match_ID.NEXTVAL, TO_DATE('2023-10-21 16:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2023-10-21 17:05', 'YYYY-MM-DD HH24:MI'));
INSERT INTO Match(Match_ID, Start_Time, End_Time) VALUES (SEQ_Match_ID.NEXTVAL, TO_DATE('2023-10-22 13:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2023-10-22 13:55', 'YYYY-MM-DD HH24:MI'));
INSERT INTO Match(Match_ID, Start_Time, End_Time) VALUES (SEQ_Match_ID.NEXTVAL, TO_DATE('2023-10-23 10:15', 'YYYY-MM-DD HH24:MI'), TO_DATE('2023-10-23 11:00', 'YYYY-MM-DD HH24:MI'));

